version: "3.8"

services:
  backend:
    volumes:
      - ./backend:/app:cached
      - backend_cargo_cache:/usr/local/cargo
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    command: cargo watch -x run

  frontend:
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
      - frontend_pnpm_store:/root/.local/share/pnpm/store
    environment:
      - VITE_API_BASE_URL=http://backend:3000/api/v1
      - CHOKIDAR_USEPOLLING=true
      - WS_NO_BUFFER_UTIL=1

  ai-engine:
    volumes:
      - ./ai-engine:/app:cached
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  backend_cargo_cache:
  frontend_node_modules:
  frontend_pnpm_store:
